### ISSUE TITLE
[Suggestion] cdk8s.yaml config file should support object version overrides

### ISSUE THREAD

**Issue by campionfellin** [awslabs/cdk8s#110]
**Is your feature request related to a problem? Please describe.**

Right now, with the CLI you can specify specific versions of `k8s` objects. For example,

```
cdk8s import k8s --language typescript --include io.k8s.api.extensions.v1beta1.Deployment
```

To specify the latest `k8s` version, except to include the `v1beta1` version of `Deployment`

**Describe the solution you'd like**

This should be possible in the `cd8ks.yaml` config.

**Describe alternatives you've considered**

I think there's a couple ways to do this:

```
app: node index.js
language: typescript
imports:
  - k8s@1.17.0 --include  io.k8s.api.extensions.v1beta1.Deployment
```

```
app: node index.js
language: typescript
imports:
  - k8s@1.17.0
include:
  -  io.k8s.api.extensions.v1beta1.Deployment
```

```
app: node index.js
language: typescript
imports:
  - k8s@1.17.0
overrides:
  - import: k8s@1.17.0
    override: io.k8s.api.extensions.v1beta1.Deployment
```

**Additional context**

Of these, I'd go with the 2nd or 3rd. The 2nd simply mimics the current functionality, while the third extends it.

I think in the future, when, say, the `knative` API objects are supported, then 3 would be the best way to do this. That being said, 2 solves the problem now, and 3 can be implemented when needed.

I'd choose (2).
