### ISSUE TITLE
[cdk8s-cli] Incorrect manifest when configuring a `StatefulSet` with `volumeClaimTemplates`

### ISSUE THREAD

**Issue by iliapolo** [awslabs/cdk8s#140]
**Describe the bug**

A `StatefulSet` that defines `VolumeClaimTemplates` is incorrectly synthesized.

**To Reproduce**

```typescript
new k8s.StatefulSet(this, 'StatefulSet', {
  spec: {
    serviceName: 'service',
    selector: {
      matchLabels: { a: 'b' }
    },
    template: {
      spec: {
        containers: [{
          name: 'hello'
        }]
      }
    },
    volumeClaimTemplates: [new k8s.PersistentVolumeClaim(this, 'VolumeClaim', {
      spec: {
        accessModes: ['ReadWriteOnce']
      },
    })]
  }
})
```

This will produce the following manifest:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdk8s-playground-volumeclaim-0db7a75b
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  clusterName: cluster
  name: cdk8s-playground-statefulset-4c20ee82
spec:
  selector:
    matchLabels:
      a: b
  serviceName: service
  template:
    spec:
      containers:
        - name: hello
  volumeClaimTemplates:
    - apiVersion: v1
      chart:
        manifestFile: cdk8splayground.k8s.yaml
      kind: PersistentVolumeClaim
      name: cdk8s-playground-volumeclaim-0db7a75b
      options:
        apiVersion: v1
        kind: PersistentVolumeClaim
        spec:
          accessModes:
            - ReadWriteOnce
```

There are two problems here:

1. `PersistentVolumeClaim` is present both as a top level resource, **and** a nested resource inside the spec of the`StatefulSet`.

2. The nested resource spec contains keys that actually make it invalid. For example, `chart`, `options`...

**Expected behavior**

According to the kubernetes [spec](https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.15.0/_definitions.json#L1178) for a `StatefulSet`, I would expect the synthesized manifest to look like so:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  clusterName: cluster
  name: cdk8s-playground-statefulset-4c20ee82
spec:
  selector:
    matchLabels:
      a: b
  serviceName: service
  template:
    spec:
      containers:
        - name: hello
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cdk8s-playground-volumeclaim-0db7a75b
      spec:
        accessModes:
          - ReadWriteOnce
``` 

**Additional context**

The problem stems from the fact that the [`volumeClaimTemplates`](https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.15.0/_definitions.json#L1178) property of the `StatefulSet` spec [references](https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.15.0/_definitions.json#L1214) a [`PersistentVolumeClaim`](https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.15.0/_definitions.json#L8886) object, which is, in a very non characteristic way, an `ApiObject` itself, rather than a simple struct.

The in turn causes the generated code to force users to create a top level `PersistentVolumeClaim` object:

```typescript
volumeClaimTemplates: [new k8s.PersistentVolumeClaim(this, 'VolumeClaim', {
      spec: {
        accessModes: ['ReadWriteOnce']
      },
    })]
```

Which in turn causes all the problems mentioned here.

As a side thought, even if the synthesis was somehow correct, the API presented here is wrong and doesn't correctly represent the mental model of the use-case, as there is no reason to create a `PersistentVolumeClaim` construct (resource), if all thats needed is to pass its spec to a parent resource. 

This implies that the generated code has to change has to change, and provide a way to simply specify the spec for the `volumeClaimTemplates` property, and not the actual construct.
