### ISSUE TITLE
[Suggestion] fix ordering in YAML output

### ISSUE THREAD

**Issue by tabern** [awslabs/cdk8s#17]
**Is your feature request related to a problem? Please describe.**
Synthesized YAML shows up out of order from standard K8s format. It technically works, but for a user familiar with K8s YAML formatting can be confusing to read.

example:
```
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myappnginx37F28063
kind: Service
apiVersion: v1
metadata:
  name: myapp.nginx.service.5f289726
```

**Describe the solution you'd like**
Follow K8s YAML formatting conventions
1. apiVersion
2. kind
3. metadata
4. spec
5. etc...

example:
```
apiVersion: v1
kind: Service
metadata:
  name: myapp.nginx.service.5f289726
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myappnginx37F28063
```

_There may be a styling guide somewhere but I can't find it - looking at [K8s documentation](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service)_
