### ISSUE TITLE
Non-autogenerated K8s service name required   

### ISSUE THREAD

**Issue by mreferre** [awslabs/cdk8s#217]
### Description of the feature or enhancement:

I would like to be able to create a K8s service with a specific name. Similar to this: 
```
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  labels:
    app: yelb-appserver
    tier: middletier
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: yelb-appserver
    tier: middletier
---
```
The above creates a service called `yelb-appserver` that the internal Kubernetes resolution can resolve as `yelb-appserver`. 

### Use Case:

I need this because some applications assume a specific dns name when they call other parts / other services. In the example below I have a UI module that assumes it can reach the appserver module by calling the `yelb-appserver` name and it expects the DNS to resolve it.  

### Proposed Solution:

None 

### Other:

Right now with CDK I am doing this: 
```
    new Service(this, 'yelb-appserver', {
      spec: {
        type: 'ClusterIP',
        ports: [ { port: 4567, targetPort: IntOrString.fromNumber(4567) } ],
        selector: yelbappserverlabel,
      }
    });
```
However the above generates a Kubernetes service name which is along the lines of `yelb-cdk8s-yelb-appserver-service-jdjjdjjf.....`. This won't work. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
