### ISSUE TITLE
'Getting Started with Typescript' documentation neglects replicas property of WebServiceOptions

### ISSUE THREAD

**Issue by dillon-odonovan** [awslabs/cdk8s#264]
### Description of the bug:

I was going through the documentation for the 'Getting Started with Typescript' example and noticed that it appears the `replicas` property of `WebServiceOptions` is not being used. 

We see several other nullable properties being assigned default values in the constructor, such as in the case of 
```ts
const port = options.containerPort || 80;
```
However, there is not an equivalent line to this for `replicas`. Instead, in the deployment spec, `replicas` is always set to 1, regardless of any user-supplied value for `replicas`.
```ts
new Deployment(this, 'deployment', {
  spec: {
    replicas: 1,
    selector: {
      matchLabels: label
    },
    template: {
      metadata: { labels: label },
      spec: {
        containers: [
          {
             name: 'app',
             image: options.image,
             ports: [ { containerPort } ]
          }
        ]
      }
    }
  }
});
```

### Reproduction Steps:

Define a `WebService` in the constructor of `MyChart` as such:
```ts
new WebService(this, "hello", {
  image: "paulbouwer/hello-kubernetes:1.7",
  replicas: 10,
});
```
This produces the following k8s manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-hello-service-cf7c398a
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello1B298237
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-hello-deployment-83984d2d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello1B298237
  template:
    metadata:
      labels:
        app: hello1B298237
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.7
          name: app
          ports:
            - containerPort: 8080
```
Note that `replicas` is set to 1, despite requesting 10 in our typescript.

### Environment:

  - **Framework Version**: 0.26.0
  - **OS**: macOS High Sierra Version 10.13.6

### Other:

I would expect a line such as 
```ts
const replicas = options.replicas || 1
```
to appear with the other assignments in the constructor, and for the deployment's spec to use
```ts
new Deployment(this, 'deployment', {
  spec: {
    replicas: replicas,
    selector: {
      matchLabels: label
    },
    template: {
      metadata: { labels: label },
      spec: {
        containers: [
          {
             name: 'app',
             image: options.image,
             ports: [ { containerPort } ]
          }
        ]
      }
    }
  }
});
```
or possibly even the shorthand, like below, depending on your style preference
```ts
new Deployment(this, 'deployment', {
  spec: {
    replicas,
    selector: {
      matchLabels: label
    },
    template: {
      metadata: { labels: label },
      spec: {
        containers: [
          {
             name: 'app',
             image: options.image,
             ports: [ { containerPort } ]
          }
        ]
      }
    }
  }
});
```

--- 

This is :bug: Bug Report
