### ISSUE TITLE
[cli] Import of resources without a `validation` creates an unusable python output

### ISSUE THREAD

**Issue by iliapolo** [awslabs/cdk8s#316]
### Description of the bug:

When a CRD has no `validation`, the generated python class does not allow passing in any options, meaning you can't configure it.

### Reproduction Steps:

Save the following CRD in a file:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: widgets.com.foo.bar
spec:
  group: com.foo.bar
  names:
    kind: Widget
    listKind: Widgets
    plural: widgets
    singular: widget
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
```

and run `cdk8s import --language python <file>`

The generated python class will look like so:

```python
class Widget(cdk8s.ApiObject, metaclass=jsii.JSIIMeta, jsii_type="generated.Widget"):
    """
    schema:
    :schema:: Widget
    """

    def __init__(self, scope: constructs.Construct, name: str) -> None:
        """Defines a "Widget" API object.

        :param scope: the scope in which to define this object.
        :param name: a scope-local name for the object.
        """
        options = WidgetOptions()

        jsii.create(Widget, self, [scope, name, options])
```

Notice that the `__init__` method does not accept any options. 

Alternatively, when generating typescript code, the `Widget` class accepts an empty interface, allowing the user to pass any specification, which is the expected behavior.

```ts
/**
 *
 *
 * @schema Widget
 */
export class Widget extends ApiObject {
  /**
   * Defines a "Widget" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: WidgetOptions = {}) {
    super(scope, name, {
      ...options,
      kind: 'Widget',
      apiVersion: 'com.foo.bar/v1',
    });
  }
}

/**
 * @schema Widget
 */
export interface WidgetOptions {
}
```

### Error Log:

No error, the generated code is unusable.

### Environment:

  - **Framework Version**: 0.26.0
  - **OS**: Any

### Other:

--- 

This is :bug: Bug Report
