### ISSUE TITLE
[cdk8s-plus-17/Deployment] spec.template.spec.volumes[1].name: Duplicate value

### ISSUE THREAD

**Issue by civilizeddev** [awslabs/cdk8s#483]
#### Actual Result

[My chart](https://github.com/civilizeddev/cdk8s-20201223/blob/b76f932d17bc8ccd3c9bcc7888003b7696fc13a3/lib/charts/mosquitto.ts#L34-L62
) generates [duplicate volume items in specs of Deployment](https://github.com/civilizeddev/cdk8s-20201223/blob/b76f932d17bc8ccd3c9bcc7888003b7696fc13a3/out/mosquitto.k8s.yaml#L74-L114
).

#### Expected Result

```
...
      volumes:
        - configMap:
            items:
              - key: "mosquitto-acl.conf"
                path: "mosquitto-acl.conf"
              - key: "mosquitto-password.conf"
                path: "mosquitto-password.conf"
              - key: "mosquitto.conf"
                path: "mosquitto.conf"
            name: "mosquitto-configmap-c863f12c"
          name: "configmap-mosquitto-configmap-c863f12c"
---
...
```

### Reproduction Steps:

Here is [my repo](https://github.com/civilizeddev/cdk8s-20201223) for this issue.

```
$ git clone https://github.com/civilizeddev/cdk8s-20201223.git
$ cd cdk8s-20201223
$ yarn
$ yarn synth
$ cat ./packages/cdk8s/out/mosquitto.k8s.yaml
```

### Error Log:

```
$ kubectl apply -f ./packages/cdk8s/out/mosquitto.k8s.yaml

The Deployment "mosquitto-deployment-c8b0646c" is invalid: 
* spec.template.spec.volumes[1].name: Duplicate value: "configmap-mosquitto-configmap-c863f12c"
* spec.template.spec.volumes[2].name: Duplicate value: "configmap-mosquitto-configmap-c863f12c"
* spec.template.spec.volumes[3].name: Duplicate value: "configmap-mosquitto-configmap-c863f12c"
```

### Environment:

  - **Framework Version**: 1.0.0-beta.5
  - **OS**: macOS Big Sur 11.1

### Other:

- [[cdk8s] Duplicated synthed resources when nesting Charts #368](https://github.com/awslabs/cdk8s/issues/368)

--- 

This is :bug: Bug Report
