### ISSUE TITLE
(cdk8s-plus ingress) support sslRedirect method.

### ISSUE THREAD

**Issue by guan840912** [awslabs/cdk8s#509]
### Description of the feature or enhancement:
`cdk8s-plus`  support `cdk8s-plus.IngressBackend.sslRedirect()` method.

### Use Case:

In `aws-load-balancer-controller` config, we need to add ssl-redirect rule in rules. 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/tasks/ssl_redirect/ 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxx:certificate/xxxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
         - path: /users/*
           backend:
             serviceName: user-service
             servicePort: 80
         - path: /*
           backend:
             serviceName: default-service
             servicePort: 80
```
### Proposed Solution:

add `cdk8s-plus.IngressBackend.sslRedirect()` method to add  ssl-redirect  rule .
```ts
    const ACM = 'arn:aws:acm:us-east-1:0123456789:certificate/1002e2eb-3444-2222-1111-xxxxxxxxxx';
    const svc = new kplus.Service(this, 'svc', {
      ports: [{port: 3000}],
    });
    const ing = new kplus.Ingress(this, 'ing', {
      metadata: {
        name: 'k8sing',
        annotations: {
          'kubernetes.io/ingress.class': 'alb',
          'alb.ingress.kubernetes.io/load-balancer-attributes': 'idle_timeout.timeout_seconds=300',
          'alb.ingress.kubernetes.io/scheme': 'internet-facing',
          'alb.ingress.kubernetes.io/certificate-arn': ACM,
          'alb.ingress.kubernetes.io/listen-ports': '[{"HTTP": 80}, {"HTTPS":443}]',
          'alb.ingress.kubernetes.io/actions.ssl-redirect': '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}',
        },
      },
    });
    ing.addRule('/*',kplus.IngressBackend.sslRedirect());
    ing.addHostRule('xxx.example.com', '/*',kplus.IngressBackend.fromService(svc));
  }
```
### Other:

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
