### ISSUE TITLE
Allow specifying module name when importing

### ISSUE THREAD

**Issue by eladb** [awslabs/cdk8s#69]
Proposed syntax: `[module=]import`.

For example, the following cdk8s.yaml file includes a bunch of imports:

```yaml
app: node index.js
language: typescript
imports:
  - k8s@1.17.0
  - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml
  - mattermost=mattermost_crd.yaml
```

- The first import (k8s API) will use the default `k8s` module name.
- The second CRD will import to `jenkins` (which is the resource kind).
- The resource kind of the Mattermost CRD is actually `ClusterInstallation`. This means that the default module name will be `clusterinstallation` so we here we want to provide an alternative and we prefix the import source with `mattermost=` which tells the CLI to use this module name instead.

**Comment by campionfellin** [comment]
I'll take this!

**Comment by campionfellin** [comment]
What about something like this?

```
app: node index.js
language: typescript
imports:
  - k8s@1.17.0
  - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml
  - modulename: mattermost
    file: mattermost_crd.yaml

```
