### ISSUE TITLE
How to use multi-line in ConfigMap?

### ISSUE THREAD

**Issue by jialechan** [awslabs/cdk8s#86]
```yaml
apiVersion: v1
data:
  kubernetes.conf: |-
    <match fluent.**>
      @type null
    </match>

kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
```
```Typescript
new ConfigMap(this, name, {
    metadata: {
        name: 'fluentd-config',
        namespace: 'kube-system'
    },
    data: ???
});
```
How to change multi-line to cdk8s?
